### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by iGetUploaded** [MGalaCyber/Discord.js-v14-Command-Handler-Template#2]
Why is the index.js encrypted like crazy?

Also it says *this source code is public* but its technically not if its encrypted

**Comment by phucho0237** [comment]
same question

**Comment by iGetUploaded** [comment]
> same question

Got most of it decompiled : )

**Comment by MGalaCyber** [comment]
# Ok so many many people always ask `why some of source code are encrypted?`

## 📕 Please Note

> Because, when someone uses the source code that I made, they never give credit to the creator, sometimes they even overwrite the credits that I have posted and use public and it's as if they made the source code of the project. That's why I encrypt some scripts in all the code projects I publish on GitHub. 
> Therefore open source sentences are useless! It's up to you whether you want the word to be useless or not, my message is when you use source code made by someone else, please give credit to the original creator of the source code you are using Because it's an illegal act!

> if you want unencrypted source code, you can buy it directly from me, or you can boost my discord server to get unencrypted source code, server link [Click Here](https://discord.gg/SMHh8SGRQN)

**Comment by iGetUploaded** [comment]
Understandable maybe just take out the text next time
